spring:
  application:
    name: jpaFundimental250820
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        format_sql: true #SQL ??? ??
        use_sql_comments: true #SQL ?? ??
        highlight_sql: true #SQL ?? ??
  output:
    ansi:
      enabled: always
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            # SQL ??? ? ???? ? ??? ??
            bind: TRACE
            # SQL ?? ? ?? ?? ??? ??
            extract: TRACE
      springframework:
        transaction:
          interceptor: TRACE